import json
import logging
from typing import Any

import httpx

from app.core.config import get_settings

logger = logging.getLogger(__name__)


class FeatherlessService:
    """
    Dedicated Featherless AI client for on-demand model decision explanations.
    Uses ultra-lightweight models (e.g. Qwen/Qwen2.5-1.5B-Instruct) to minimize credit usage.
    Never invokes Gemini API. Strictly grounded in provided decision context.
    """

    def __init__(self) -> None:
        self.settings = get_settings()

    @property
    def api_key(self) -> str:
        return self.settings.featherless_api_key

    @property
    def model(self) -> str:
        return self.settings.featherless_model or "Qwen/Qwen2.5-1.5B-Instruct"

    @property
    def api_url(self) -> str:
        return self.settings.featherless_api_url or "https://api.featherless.ai/v1/chat/completions"

    @property
    def timeout(self) -> int:
        return self.settings.featherless_timeout_seconds or 30

    def is_configured(self) -> bool:
        return bool(self.api_key and self.api_key != "changeme")

    def _build_explanation_prompt(
        self,
        decision_context: dict[str, Any],
        user_query: str | None = None,
    ) -> str:
        """
        Build a grounded prompt that instructs the model to explain:
        1. What decision was made
        2. Why it was made
        3. What factors/constraints influenced it
        Strictly adhering to provided facts without hallucinating.
        """
        query_text = user_query.strip() if user_query else "Why was this decision made?"
        context_json = json.dumps(decision_context, indent=2, default=str)

        return (
            "You are an AI Decision Explainer for StudentLife OS.\n"
            "Your role is to clearly, concisely, and transparently explain why an autonomous decision was made.\n\n"
            "DECISION CONTEXT (Ground Truth):\n"
            f"{context_json}\n\n"
            f"USER QUERY:\n\"{query_text}\"\n\n"
            "STRICT INSTRUCTIONS:\n"
            "1. Answer the user's inquiry based ONLY on the provided Decision Context above. DO NOT invent, assume, or extrapolate facts that are not present.\n"
            "2. Structure your explanation clearly into three brief points:\n"
            "   - What decision was made\n"
            "   - Why it was made\n"
            "   - What factors/constraints influenced it (e.g. deadline urgency, user schedule conflicts, course weights, existing tasks)\n"
            "3. Keep the tone professional, objective, and concise. Avoid unnecessary preamble."
        )

    async def explain_decision(
        self,
        decision_context: dict[str, Any],
        user_query: str | None = None,
    ) -> str:
        """
        Generate an elaborated explanation of a model decision using Featherless AI.
        """
        if not self.is_configured():
            return (
                "⚠️ Featherless AI API key is not configured. "
                "Brief reason on record: " + str(decision_context.get("brief_reason") or "No reason available.")
            )

        prompt = self._build_explanation_prompt(decision_context, user_query)
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You explain AI decisions for StudentLife OS concisely and accurately "
                        "based strictly and exclusively on the provided context. Never hallucinate reasoning."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
            "max_tokens": 300,
        }

        try:
            async with httpx.AsyncClient(timeout=float(self.timeout)) as client:
                response = await client.post(self.api_url, headers=headers, json=payload)
                if response.status_code == 200:
                    data = response.json()
                    choices = data.get("choices", [])
                    if choices and "message" in choices[0]:
                        explanation = choices[0]["message"].get("content", "").strip()
                        if explanation:
                            return explanation
                    return "No explanation generated by model."
                else:
                    logger.error(
                        "Featherless AI error: status %d, response: %s",
                        response.status_code,
                        response.text,
                    )
                    brief = decision_context.get("brief_reason") or "Autonomous action completed."
                    return (
                        f"⚠️ Explanation service temporarily unavailable (status {response.status_code}).\n"
                        f"Brief reason: {brief}"
                    )
        except Exception as err:
            logger.error("Failed to connect to Featherless AI: %s", err)
            brief = decision_context.get("brief_reason") or "Autonomous action completed."
            return (
                f"⚠️ Could not reach Featherless AI explanation service ({err}).\n"
                f"Brief reason: {brief}"
            )
