from datetime import datetime
from typing import Any, Literal
from pydantic import BaseModel, Field

from app.schemas.gemini_schemas import ExtractedDeadlineItem, ExtractedTaskItem


class NormalizedEmail(BaseModel):
    """Normalized email data structure passed into OpenClaw reasoning layer."""
    message_id: str = Field(..., description="Unique message ID / Gmail ID")
    thread_id: str | None = Field(None, description="Thread identifier")
    sender: str = Field(..., description="Display name or raw sender string")
    sender_email: str | None = Field(None, description="Extracted sender email address")
    subject: str = Field(..., description="Email subject")
    timestamp: str = Field(..., description="Date/time email was sent or received")
    body: str = Field(..., description="Plain-text body content of the email")
    attachments: list[str] = Field(default_factory=list, description="Attachment filenames or metadata")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional headers or metadata")


class TaskUpdateItem(BaseModel):
    """Specifies an update or extension to an existing task rather than creating a duplicate."""
    existing_task_id: int | None = Field(None, description="ID of matching task if known")
    matching_title_query: str = Field(..., description="Title substring to match existing task (e.g., 'Assignment 2')")
    new_title: str | None = Field(None, description="Updated title if changed")
    new_deadline: datetime | None = Field(None, description="Updated or extended deadline")
    new_priority: Literal["low", "medium", "high", "urgent"] | None = Field(None, description="Updated priority")
    update_reason: str = Field(..., description="Why this task was modified (e.g. 'Deadline extended by 24h')")


class CalendarEventItem(BaseModel):
    """Calendar event to schedule or modify."""
    title: str = Field(..., description="Event or meeting title")
    starts_at: datetime = Field(..., description="Start datetime (ISO 8601)")
    ends_at: datetime = Field(..., description="End datetime (ISO 8601)")
    description: str | None = Field(None, description="Event details or meeting link")
    location: str | None = Field(None, description="Location or virtual platform")


class EmailDraftItem(BaseModel):
    """Draft email reply generated by LLM reasoning for human review."""
    to: str = Field(..., description="Recipient email address")
    subject: str = Field(..., description="Draft subject line")
    body: str = Field(..., description="Draft message text")


class EmailReasoningDecision(BaseModel):
    """Structured decision output from LLM/Featherless AI reasoning."""
    priority: Literal["low", "medium", "high", "urgent"] = Field(
        "medium", description="Priority level of the email and required actions"
    )
    requires_action: bool = Field(
        False, description="True if this email warrants task creation, deadline update, or response"
    )
    summary: str = Field(..., description="High-level 1-sentence summary of the email")
    reasoning: str = Field(
        ..., description="Clear, concise explanation for why this priority and action was decided"
    )
    deadlines: list[ExtractedDeadlineItem] = Field(
        default_factory=list, description="All explicit deadlines extracted from the email"
    )
    tasks_to_create: list[ExtractedTaskItem] = Field(
        default_factory=list, description="New tasks to be added to the student's task database"
    )
    tasks_to_update: list[TaskUpdateItem] = Field(
        default_factory=list, description="Existing tasks whose deadlines or details should be updated"
    )
    events_to_create: list[CalendarEventItem] = Field(
        default_factory=list, description="Calendar events or meetings that should be scheduled"
    )
    detected_conflicts: list[str] = Field(
        default_factory=list, description="Conflicts with existing schedule or pending tasks"
    )
    recommended_action: str = Field(
        "no_action_needed",
        description="Recommended action: create_task, update_deadline, schedule_event, draft_reply, or review",
    )
    draft_response_needed: bool = Field(
        False, description="True if drafting an email response is recommended"
    )
    draft_response: EmailDraftItem | None = Field(
        None, description="Content of the drafted email response if applicable"
    )
