import { FormEvent, useState } from 'react';
import { api, type ProfileInput, type ProfileResponse } from '../api/client';

type Props = { profile: ProfileResponse; onSaved: (profile: ProfileResponse) => void };

export default function Onboarding({ profile, onSaved }: Props) {
  const current = profile.profile;
  const [form, setForm] = useState<ProfileInput>({ full_name: profile.user.full_name, timezone: current?.timezone ?? 'Asia/Kolkata', college: current?.college ?? '', degree: current?.degree ?? '', year: current?.year, cgpa: current?.cgpa, target_roles: current?.target_roles ?? '', target_companies: current?.target_companies ?? '', skills: current?.skills ?? '', preferred_locations: current?.preferred_locations ?? '', available_study_hours: current?.available_study_hours, preferred_study_times: current?.preferred_study_times ?? '', notification_preferences: current?.notification_preferences ?? '' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const set = (key: keyof ProfileInput, value: string) => setForm((state) => ({ ...state, [key]: ['year', 'cgpa', 'available_study_hours'].includes(key) ? (value === '' ? undefined : Number(value)) : value }));

  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError(null);
    try { onSaved(await api.saveProfile(form, current?.id)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to save profile.'); } finally { setSaving(false); }
  }

  return <section className="onboarding"><div className="section-heading"><div><p className="eyebrow">{current ? 'Edit your context' : 'First, tell us about you'}</p><h2>{current ? 'Profile details' : 'Build your student profile'}</h2></div></div><p className="muted">This stays in your local workspace and helps Student Life OS plan around your real constraints.</p>{error && <div className="notice error" role="alert">{error}</div>}<form onSubmit={submit} className="profile-form"><label>Name<input required value={form.full_name ?? ''} onChange={(event) => set('full_name', event.target.value)} /></label><label>Timezone<input value={form.timezone ?? ''} onChange={(event) => set('timezone', event.target.value)} /></label><label>College<input value={form.college ?? ''} onChange={(event) => set('college', event.target.value)} /></label><label>Degree<input value={form.degree ?? ''} onChange={(event) => set('degree', event.target.value)} /></label><label>Year<input type="number" min="1" max="10" value={form.year ?? ''} onChange={(event) => set('year', event.target.value)} /></label><label>CGPA<input type="number" min="0" max="10" step="0.01" value={form.cgpa ?? ''} onChange={(event) => set('cgpa', event.target.value)} /></label><label>Target roles<input placeholder="e.g. product analyst, backend intern" value={form.target_roles ?? ''} onChange={(event) => set('target_roles', event.target.value)} /></label><label>Target companies<input value={form.target_companies ?? ''} onChange={(event) => set('target_companies', event.target.value)} /></label><label>Skills<input placeholder="Comma-separated" value={form.skills ?? ''} onChange={(event) => set('skills', event.target.value)} /></label><label>Preferred locations<input value={form.preferred_locations ?? ''} onChange={(event) => set('preferred_locations', event.target.value)} /></label><label>Study hours per day<input type="number" min="0" max="24" step="0.5" value={form.available_study_hours ?? ''} onChange={(event) => set('available_study_hours', event.target.value)} /></label><label>Preferred study times<input placeholder="e.g. mornings, 7-10pm" value={form.preferred_study_times ?? ''} onChange={(event) => set('preferred_study_times', event.target.value)} /></label><label className="wide">Notification preferences<input placeholder="e.g. Telegram, email, quiet hours" value={form.notification_preferences ?? ''} onChange={(event) => set('notification_preferences', event.target.value)} /></label><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : current ? 'Save profile' : 'Continue to workspace'}</button></form></section>;
}
